POST http://localhost:3000/login
content-Type: application/json

{
    "username" : "amarboy",
    "password" : "gohome"

}

###

GET http://localhost:3000/bye

###

GET http://localhost:3000


###
POST http://localhost:3000/register
content-Type: application/json

{
    "username" : "safwan",
    "password" : "qwaszx21",
    "name" : "safwang",
    "email" : "mohdsafwan@gmail.com"
}
